export const GET_RANDOM_PHOTO_REQUEST = 'GET_RANDOM_PHOTO_REQUEST';
export const GET_RANDOM_PHOTO_SECCESS = 'GET_RANDOM_PHOTO_SECCESS';
export const GET_GRAY_PHOTO = 'GET_GRAY_PHOTO';
export const GET_BLURE1_PHOTO = 'GET_BLURE1_PHOTO';
export const GET_BLURE2_PHOTO = 'GET_BLURE2_PHOTO';
export const GET_FILTERED_PHOTO_SECCESS = 'GET_FILTERED_PHOTO_SECCESS';
export const GET_NORMAL_PHOTO = 'GET_NORMAL_PHOTO';